version: "3.9"

services:
  backend-api-server:
    build:
      context: ./backend-api-server
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    environment:
      - SERVER_PORT=3500
      - LOG_LEVEL=info
      - DB_USER=postgres
      - DB_PASSWORD=secretpass
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z db 5432"]
      interval: 10s
      timeout: 5s
      retries: 5

  task-exec-agent:
    build:
      context: ./task-exec-agent
      dockerfile: Dockerfile
    ports:
      - "3000"
    environment:
      - BACKEND_API_HOST=backend-api-server
      - BACKEND_API_PORT=3500
      - POLL_INTERVAL=5s
      - LOG_LEVEL=info
    depends_on:
      backend-api-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://backend-api-server:3500 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
